#!/home/amine/Downloads/Projet_data_science_TM/venv/bin/python3.10
import sys
from lib2to3.main import main

sys.exit(main("lib2to3.fixes"))
